import { BarChart3, Bot, Image, PenTool, TestTube, Webhook, Wrench } from "lucide-react"
import type { IconType } from "react-icons"
import { FaAws, FaCss3, FaDumbbell, FaFutbol, FaGamepad, FaJava, FaPersonSwimming } from "react-icons/fa6"
import { GiBoxingGlove, GiCookingPot } from "react-icons/gi"
import {
  SiBetterauth,
  SiC,
  SiClaude,
  SiCloudflare,
  SiCplusplus,
  SiDavinciresolve,
  SiDocker,
  SiFigma,
  SiGit,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiLua,
  SiMongodb,
  SiNeovim,
  SiNextdotjs,
  SiNodedotjs,
  SiObsidian,
  SiPosthog,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiRust,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si"
import { TbDatabase } from "react-icons/tb"

const TECH_ICONS: Record<string, IconType> = {
  react: SiReact,
  nextdotjs: SiNextdotjs,
  "next.js": SiNextdotjs,
  typescript: SiTypescript,
  tailwindcss: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  html5: SiHtml5,
  html: SiHtml5,
  css3: FaCss3,
  css: FaCss3,
  git: SiGit,
  "git & github": SiGit,
  mongodb: SiMongodb,
  nodedotjs: SiNodedotjs,
  "node.js": SiNodedotjs,
  python: SiPython,
  redis: SiRedis,
  docker: SiDocker,
  amazonaws: FaAws,
  aws: FaAws,
  graphql: SiGraphql,
  prisma: SiPrisma,
  claude: SiClaude,
  "claude code": SiClaude,
  cloudflare: SiCloudflare,
  lua: SiLua,
  neovim: SiNeovim,
  "rest-apis": Webhook,
  "rest apis": Webhook,
  analytics: BarChart3,
  testing: TestTube,
  "testing libraries": TestTube,
  javascript: SiJavascript,
  java: FaJava,
  cplusplus: SiCplusplus,
  "c++": SiCplusplus,
  figma: SiFigma,
  obsidian: SiObsidian,
  stripe: SiStripe,
  betterauth: SiBetterauth,
  "better-auth": SiBetterauth,
  posthog: SiPosthog,
  davinciresolve: SiDavinciresolve,
  "davinci resolve": SiDavinciresolve,
  rust: SiRust,
  c: SiC,
  sql: TbDatabase,
  cooking: GiCookingPot,
  gym: FaDumbbell,
  "video games": FaGamepad,
  boxing: GiBoxingGlove,
  soccer: FaFutbol,
  swimming: FaPersonSwimming,
  chatgpt: Bot,
  "adobe illustrator": PenTool,
  "adobe photoshop": Image,
}

/** ponytail: covers common tech names; unmapped skills fall back to a generic icon. */
export function getTechIcon(iconKeyOrName: string): IconType {
  const key = iconKeyOrName.trim().toLowerCase()
  return TECH_ICONS[key] ?? Wrench
}
